### ISSUE TITLE
No runtime reducing with TensorRT5/CUDA10/cuDNN7.3 on Jetson Xavier

### ISSUE THREAD

**Issue by JerryJiaGit** [JerryJiaGit/facenet_trt#3]
No runtime reducing with TensorRT5/CUDA10/cuDNN7.3 on Jetson Xavier.

L4T 4.1.1
TensorFlow 1.12.0
TensorRT 5.0.3

Can enabled TensorRT convert with same code, but there is no runtime reducing with TensorRT5/CUDA10/cuDNN7.3 on Jetson Xavier.

For inception-resnet v1 network saved model convert:
Original: 0.0428 s
TensorRT FP16: 0.04263 s

Will try x86 TRT5 and check with NVIDIA TRT team later.

**Comment by nick3761** [comment]
Hi @JerryJiaGit ,

Let's track this issue together.
Thank you very much for your help.


Thanks,
Nick

**Comment by JerryJiaGit** [comment]
@nick3761 
I have done some testing today and I can see about 20% runtime reducing with TRT enabled on my Xavier for embedding.

I have done some minor changes, not sure if impacts speed, but could you try my latest code (face.py and facenet.py)? 

My result:
Original - avg 0.045555299 s
TensorRT SavedModel FP16 - avg 0.036991812 s

Thanks,.
Jerry

**Comment by nick3761** [comment]
Hi @JerryJiaGit ,

I used the content you modified, but the efficiency has not improved.
Original and TensorRT are both in the range of 0.06-0.07.
Is there something I am missing to modify?

Jerry Jia [01/21/2019] Change SavedModel max_batch_size=1 same as Ckpt, changed workspace mem to 1GB (1<<20)
Jerry Jia [01/21/2019] Changed input:0 to batch_join:0 for embedding and set GPU gpu_memory_fraction = 0.3

Can I ask what is the intention to modify "Changed input:0 to batch_join:0"?

Thanks,
Nick

**Comment by JerryJiaGit** [comment]
For batch_join:0, it is for TensorRT 5 on my x86_64 machine, original input:0 was reported unavailable input. So I changed it to batch_join as David suggested. And new change also works with original TRT4 or without TRT enabled. 

It is a little strange that you didn't see any improvement, did you get the identity runtime from face.py? And the 60ms~ for one embedding is a little slower than mine (160px embedding). Are you using latest l4t 4.1.1 and tensorflow 1.12 with TRT5? And please note, there will not be improvement with ckpt and meta graph. Improvement is only for .pb savedmodel.

See my result:
- TensorRT enabled:
720_400cm.JPG identify,7.786341905593872
720_400cm.JPG identify,0.03982114791870117
720_400cm.JPG identify,0.03882241249084473
720_400cm.JPG identify,0.03966045379638672
720_400cm.JPG identify,0.037313222885131836
720_400cm.JPG identify,0.03514575958251953
720_400cm.JPG identify,0.038045406341552734
720_400cm.JPG identify,0.03360748291015625
720_400cm.JPG identify,0.03802132606506348
720_400cm.JPG identify,0.033812522888183594
720_400cm.JPG identify,0.038179874420166016
720_400cm.JPG identify,0.038529157638549805
720_400cm.JPG identify,0.03843092918395996
720_400cm.JPG identify,0.03988981246948242
720_400cm.JPG identify,0.03449368476867676
720_400cm.JPG identify,0.0355379581451416
720_400cm.JPG identify,0.03583407402038574
720_400cm.JPG identify,0.03281998634338379
720_400cm.JPG identify,0.03812074661254883
720_400cm.JPG identify,0.03677654266357422

- TensorRT Disabled:
720_400cm.JPG identify,2.0181920528411865
720_400cm.JPG identify,0.04379844665527344
720_400cm.JPG identify,0.03994297981262207
720_400cm.JPG identify,0.03880190849304199
720_400cm.JPG identify,0.04565834999084473
720_400cm.JPG identify,0.040978431701660156
720_400cm.JPG identify,0.04432106018066406
720_400cm.JPG identify,0.04065895080566406
720_400cm.JPG identify,0.040050506591796875
720_400cm.JPG identify,0.03969907760620117
720_400cm.JPG identify,0.04155468940734863
720_400cm.JPG identify,0.04369688034057617
720_400cm.JPG identify,0.042081356048583984
720_400cm.JPG identify,0.03946805000305176
720_400cm.JPG identify,0.04174447059631348
720_400cm.JPG identify,0.04349660873413086
720_400cm.JPG identify,0.038466691970825195
720_400cm.JPG identify,0.03952455520629883
720_400cm.JPG identify,0.043088674545288086
720_400cm.JPG identify,0.04778766632080078

So if didn't consider the first long init time, we still can see improvement with TRT enabled.

**Comment by nick3761** [comment]
Hi @JerryJiaGit ,

Sorry, I am using my own program to get the feature.
But "facenet.py" is using yours, I also have the part that changes my code "Changed input:0 to batch_join:0 for embedding and set GPU gpu_memory_fraction = 0.3"

I will try "face.py", thank you very much for your guidance.

Thanks,
Nick

**Comment by JerryJiaGit** [comment]
@nick3761 
Today, I also have some update for ckpt/meta graph, you can download face.py and facenet.py again and have a try.

I have same test on jetson, it works as expected. Now ckpt/meta graph and SavedModel both works with run-time improvement with TRT convert.

Thanks.

**Comment by JerryJiaGit** [comment]
No response, closed. 
Feel free to re-open if any need.
