### ISSUE TITLE
run

### ISSUE THREAD

**Issue by SinghiDivyanshu** [JerryJiaGit/facenet_trt#7]
hi, thanks in advance 

how to run the program? can you provide steps to run the program.

**Comment by JerryJiaGit** [comment]
hi, thanks for your suggestion. This is an update and modified based on facenet, here is more details of steps:

1. Get GPU cuda/cudnn, tensorflow-gpu and TensorRT ready
2. Get facenet ready with https://github.com/davidsandberg/facenet ready
3. Could download here facenet.py, face.py (optional), /align/detect_face.py and replace original files.

Hope it helps. Anyway, I will update usage for a better description.

**Comment by JerryJiaGit** [comment]
Usage was updated, so if there is no new request, I will close this issue in next week.
